{
	"version": 1528836840,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/fondo.png",
		"images/player-sheet0.png",
		"images/bala-sheet0.png",
		"images/explosion-sheet0.png",
		"images/zombie-sheet0.png",
		"images/fondogameover.png",
		"images/fondopausa-sheet0.png",
		"images/fondoinicio.png",
		"images/tiledbackground2.png",
		"images/fondocreditos.png",
		"images/tiledbackground.png",
		"images/fondoranking.png",
		"images/icezombie-sheet0.png",
		"images/zombieboss-sheet0.png",
		"images/mouseleft-sheet0.png",
		"images/fondowin.png",
		"images/teclas-sheet0.png",
		"images/derecha-sheet0.png",
		"images/izquierda-sheet0.png",
		"images/arriba-sheet0.png",
		"images/abajo-sheet0.png",
		"media/disparo_1.m4a",
		"media/disparo_1.ogg",
		"media/game over.m4a",
		"media/game over.ogg",
		"media/zombie muere.m4a",
		"media/zombie muere.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}